### ISSUE TITLE
Bug: XML Output of Drum Tab Has Wrong Notes

### ISSUE THREAD

**Issue by MaishaRahman98** [joshgenat/2311_Group7#15]
**ID:** #15
**Who Raised the Bug:** Maisha Rahman
**Version:** 4bb5575
**Title:** XML Output of Drum Tab Has Wrong Notes
**Platform:** Windows 10
**Reproduction Steps:**
How the bug was found, and how to recreate it:
1. Run the application
2. In the _Tab_ window, click on _Select File_
- Select 
[drumexample.txt](https://github.com/joshgenat/2311_Group7/files/6192580/drumexample.txt)

3. Click on _Convert_
4. Click on _Download_, and save the MusicXML file
5. Upload the MusicXML file in the MusicXML viewer called MusicOpenSheetDisplay Demo (link: https://opensheetmusicdisplay.github.io/demo/)

**Expected Outcome:**
![image](https://user-images.githubusercontent.com/77294562/112214883-16764f00-8bf6-11eb-820d-6b839ba9f9c3.png)

**Actual Outcome:**
![image](https://user-images.githubusercontent.com/77294562/112214925-22faa780-8bf6-11eb-9b85-73bf71aafa59.png)

**Priority:**
Please implement showing the correct drum notes in the MusicXML output from input text tabs like drumexample.txt.
**Severity:**
Medium

**Comment by Uthith18** [comment]
Thank you for reporting this bug, It  also seems  like the "actual output"  didn't read voice number correctly. We will be sure to fix this issue in our next update. 

- Uthith
