### ISSUE TITLE
Bug: UI adjusting window size error not showing text area

### ISSUE THREAD

**Issue by ljaypals** [joshgenat/2311_Group7#16]
**ID:** #16
**Reporter:** Lars Jaylen Palalon email: ljaypals@my.yorku.ca
**Version:** [4bb5575](https://github.com/joshgenat/2311_Group7/commit/4bb55750c1ebac6709ff6185a74ff044ec652a2f)
**Title:** UI adjusting window size error not showing text area
**Platform:** Windows 10
**Reproduction:** It was found when adjusting the window by pulling the window from its left or right side and it is not showing the text area.

**Expected Result:**
Somewhat similar to this smaller window version
![Screenshot 2021-03-23 231241](https://user-images.githubusercontent.com/77308877/112249057-79cfa380-8c2d-11eb-902e-d262bab1f7b1.png)

**Actual Result:**
![Screenshot 2021-03-23 231311](https://user-images.githubusercontent.com/77308877/112249097-8bb14680-8c2d-11eb-9c67-d30c403281a0.png)

**Priority:** Please make it so that the window has a fixed small size so the text area can be seen and everything doesn't collide with each other.

**Severity:** low

**Comment by joshgenat** [comment]
Thanks for pointing that out! We have already fixed this issue which will be shown in the next release!
