### ISSUE TITLE
Time signature is fixed at 6/8 time

### ISSUE THREAD

**Issue by Stan15** [joshgenat/2311_Group7#19]
## Title
The time signature is fixed at 6/8 time

## Version 
1.0? no versioning for this project

## Platform 
Windows 10, Eclipse, JavaSE 15.0.2

## Error Description
When a time signature is put into the "beats" and "beat type" text fields, the time signature still remains at 6/8 time

## Steps to reproduce
1. Run the application
2. Paste in the tablature
3. Set the text in the "beats" and the  "best-type" text fields to 4 and 4 (or any other set of values other than 6 and 8)
4. Click the "Convert" button
5. Open the MusicXML file in a text editor or in musescore if you have a discerning ear for time signature differences

## Input
```
e|-------------0----------|-----------------------------|
B|--0----2--4-------3--1--|--0--------------------------|
G|------------------------|-------2--0----------0--0----|
D|------------------------|-------------4-5-4------0----|
A|------------------------|-------3-----5----------2----|
E|--3----2-----0----2-----|--3---------------------3----|
```

## Expected
The beats tag of any given note should be 4 and the beat-type tag should also be 4.
## Actual
The beats tag and beat-type tags are always 6 and 8 respectively, regardless of the values input for beats and beat type

## Priority
High

## Severity
High

### text input file
[timeSigTabText.txt](https://github.com/joshgenat/2311_Group7/files/6194668/timeSigTabText.txt)

### musicxml
[testTimeSig.txt](https://github.com/joshgenat/2311_Group7/files/6194670/testTimeSig.txt)

**Comment by AndyLin-1** [comment]
Thank you for reporting this issue, We realized we didn't set the time signature after getting it from the UI. This will be fixed for next deployment.
