### ISSUE TITLE
GUI Issue

### ISSUE THREAD

**Issue by tens-ml** [joshgenat/2311_Group7#23]
<h1>GUI Bug Report</h1>
<p><b>Description:</b>  GUI loads with some of the buttons cut off/text not fully rendered</p>
<p><b>Actual Behavior:</b>  Select File and download buttons do not display properly</p>
<p><b>Expected Behavior:</b> Select File and Download button should be visible with their full text </p>
<p><b>Steps to Reproduce:</b>  Simply run the application with gradle</p>
<p><b>Priority:</b> Medium </p>
<p><b>Status:</b> Ready for development </p>
<p><b>Images:</b> </p>

![](https://i.imgur.com/yGIYy4O.png)
 </p>

**Comment by joshgenat** [comment]
Thanks for pointing that out! We have already fixed this issue which will be shown in the next release!
