### ISSUE TITLE
Bug: UI Issue

### ISSUE THREAD

**Issue by tens-ml** [joshgenat/2311_Group7#25]
<h1>UI Bug</h1>
<p> 
<b>Description:</b>  Beat type label is cut off by text field when program loads
</p>
<p> 
<b>Actual Behavior:</b>  Beat field label is cut off by text field
</p>
<p> 
<b>Expected Behavior:</b>  Should be space between label and text field (as there is for "Beats")
</p>
<p> 
<b>Steps to Reproduce:</b> Simply load GUI and then it should be overlapping
</p>
<p> 
<b>Priority:</b> Low
</p>
<p> 
<b>Status:</b> Ready for development
</p>
<p>
<b>Images:</b>

![](https://i.imgur.com/MPQSGeC.png)

</p>

**Comment by joshgenat** [comment]
Thanks for pointing that out! We have already fixed this issue which will be shown in the next release!
