### ISSUE TITLE
Bug: TextFeid oversize 

### ISSUE THREAD

**Issue by Shawnli3287** [joshgenat/2311_Group7#4]
Name
Interface gui error

Description
The TextFeild is beyond the boundary

Steps to reproduce
Run the main as java application, on the main interface UI 

Expected result
Simple and well-arranged user interface UI

Actual result
TextFeild oversize and blocked part of the textarea

Priority
Lower-middle

Status
Ready for development.

Screenshot
<img width="176" alt="Screen Shot 2021-03-22 at 9 45 19 PM" src="https://user-images.githubusercontent.com/46501533/112081409-fe50f200-8b59-11eb-89fa-7983a6107328.png">

**Comment by joshgenat** [comment]
Thanks for pointing that out! We have already fixed this issue which will be shown in the next release!
