### ISSUE TITLE
Bug: UI button problem

### ISSUE THREAD

**Issue by Shawnli3287** [joshgenat/2311_Group7#5]
Name
Interface gui button text problem

Description
The text of the button is unclear and some part is hide

Steps to reproduce
Run the main as java application, on the main interface UI

Expected result
Simple and well-arranged user interface UI

Actual result
For Select and Download button is unclear and it is been Hidden

Priority
Lower-middle

Status
Ready for development.

Screenshot
<img width="113" alt="Screen Shot 2021-03-22 at 9 45 25 PM" src="https://user-images.githubusercontent.com/46501533/112082522-ee3a1200-8b5b-11eb-9d41-f4e37d14e40d.png">

**Comment by joshgenat** [comment]
Thanks for pointing that out! We have already fixed this issue which will be shown in the next release!
